version: '3.10'

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    #      args:
#    #        YML_ENV_NAME: ${VECTORIZED_ENV_NAME}
#    #        GITHUB_KEY: ${GITHUB_KEY}
#    depends_on:
#      - postgres
#    ports:
#      - ${PORT}:${PORT}
#    environment: # Add environment variables if necessary
#      - APP=${APP}
#      - PORT=${PORT}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#
#    command: ["uvicorn", "${APP}", "--host", "0.0.0.0", "--port", "${PORT}", "--reload"]





  #  redis:
  #    image: redis:latest
  #    ports:
  #      - "6380:6379"

  #  dask-scheduler:
  #    image: daskdev/dask
  #    command: dask-scheduler
  #    ports:
  #      - "8786:8786"
  #      - "8787:8787"

  #  dask-worker:
  #    image: daskdev/dask
  #    command: dask-worker --nthreads 2 --memory-limit 1GB tcp://dask-scheduler:8786
  #    depends_on:
  #      - dask-scheduler



